apiVersion: v1
kind: Secret
metadata:
  name: mysql-custom-auth  
  namespace: mysql
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: mysql123
---
apiVersion: kubedb.com/v1
kind: MySQL
metadata:
  name: mysql-cluster
  namespace: mysql
spec:
  version: "8.0.35"
  replicas: 1

  # Use externally managed auth secret
  authSecret:
    name: mysql-custom-auth
    externallyManaged: true

  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

  serviceTemplates:
    - alias: primary
      metadata:
        annotations:
          metallb.io/address-pool: newip
      spec:
        type: LoadBalancer
        ports:
          - name: mysql
            port: 3306
