apiVersion: v1
kind: Secret
metadata:
  name: redis-custom-auth
  namespace: redis
type: kubernetes.io/basic-auth
stringData:
  username: default
  password: redis123
---
apiVersion: kubedb.com/v1
kind: Redis
metadata:
  name: redis-cluster
  namespace: redis
spec:
  version: "8.2.2"
  mode: Standalone
  replicas: 1

  authSecret:
    name: redis-custom-auth
    externallyManaged: true

  storageType: Durable
  storage:
    storageClassName: local-path
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi

  serviceTemplates:
    - alias: primary
      metadata:
        annotations:
          metallb.io/address-pool: cinderip
      spec:
        type: LoadBalancer
        ports:
          - name: redis
            port: 6379
